"""Generate a small SYNTHETIC EEG fixture so the pipeline can be smoke-tested
offline.

This is not data.  It is simulated noise with a deliberately planted occipital
alpha difference, written in the same EDF layout as eegmmidb so that every
downstream module can be exercised without network access.

Nothing produced from this fixture is a scientific result, and the pipeline
enforces that: download_data.py stamps provenance as synthetic, and
config.output_dirs() then redirects all output into figures/_smoke and
results/_smoke, where visualization.py additionally watermarks every figure.

The signal model is intentionally crude:
  * 1/f background, generated by filtering white noise
  * a Gaussian alpha bump near 10 Hz, larger at posterior channels
  * the bump is amplified in the eyes-closed run
  * a slow drift and occasional high-amplitude transients so that the
    bad-channel and epoch-rejection code paths actually fire
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src import config as cfg  # noqa: E402

# The 64-channel eegmmidb montage, in file order, with the dot padding that
# the real EDF headers use (Fc5., C5.., ...) so the name-cleaning code path in
# preprocessing.py is exercised too.
CHANNELS_10_10 = [
    "Fc5.", "Fc3.", "Fc1.", "Fcz.", "Fc2.", "Fc4.", "Fc6.",
    "C5..", "C3..", "C1..", "Cz..", "C2..", "C4..", "C6..",
    "Cp5.", "Cp3.", "Cp1.", "Cpz.", "Cp2.", "Cp4.", "Cp6.",
    "Fp1.", "Fpz.", "Fp2.", "Af7.", "Af3.", "Afz.", "Af4.", "Af8.",
    "F7..", "F5..", "F3..", "F1..", "Fz..", "F2..", "F4..", "F6..", "F8..",
    "Ft7.", "Ft8.", "T7..", "T8..", "T9..", "T10.", "Tp7.", "Tp8.",
    "P7..", "P5..", "P3..", "P1..", "Pz..", "P2..", "P4..", "P6..", "P8..",
    "Po7.", "Po3.", "Poz.", "Po4.", "Po8.", "O1..", "Oz..", "O2..", "Iz..",
]

POSTERIOR = {"O1..", "Oz..", "O2..", "Iz..", "Po7.", "Po3.", "Poz.", "Po4.",
             "Po8.", "P7..", "P5..", "P3..", "P1..", "Pz..", "P2..", "P4..",
             "P6..", "P8.."}
FRONTAL = {"Fp1.", "Fpz.", "Fp2.", "Af7.", "Af3.", "Afz.", "Af4.", "Af8."}

DURATION_S = 61.0
ALPHA_HZ = 10.0


def _pink(rng: np.random.Generator, n: int, sfreq: float) -> np.ndarray:
    """White noise shaped to roughly 1/f in amplitude."""
    spec = np.fft.rfft(rng.standard_normal(n))
    freqs = np.fft.rfftfreq(n, 1.0 / sfreq)
    scale = np.ones_like(freqs)
    scale[1:] = 1.0 / np.sqrt(freqs[1:])
    out = np.fft.irfft(spec * scale, n=n)
    return out / (np.std(out) + 1e-12)


def _alpha_bump(rng: np.random.Generator, n: int, sfreq: float,
                centre: float, amp: float) -> np.ndarray:
    """A narrowband oscillation with wandering phase and amplitude."""
    t = np.arange(n) / sfreq
    phase = np.cumsum(rng.standard_normal(n)) * 0.02
    envelope = 1.0 + 0.5 * np.sin(2 * np.pi * 0.2 * t + rng.uniform(0, 6.28))
    return amp * envelope * np.sin(2 * np.pi * centre * t + phase)


_POSITIONS: np.ndarray | None = None


def _channel_positions() -> np.ndarray:
    """3D sensor positions for the 64 fixture channels, from the montage."""
    global _POSITIONS
    if _POSITIONS is None:
        import mne

        montage = mne.channels.make_standard_montage(cfg.MONTAGE)
        pos = montage.get_positions()["ch_pos"]
        canon = {k.lower(): k for k in pos}
        out = []
        for ch in CHANNELS_10_10:
            bare = ch.rstrip(".").lower()
            out.append(pos[canon[bare]])
        _POSITIONS = np.asarray(out, dtype=float)
    return _POSITIONS


def _leadfield(source_xyz: np.ndarray, spread: float = 0.055) -> np.ndarray:
    """Gaussian spatial weighting from one source to every sensor.

    Crude but sufficient: what matters is that a single source reaches many
    electrodes, so that neighbouring channels end up genuinely correlated the
    way real EEG channels are.  Independent per-channel noise would make every
    channel look broken to a correlation-based bad-channel rule.
    """
    d = np.linalg.norm(_channel_positions() - source_xyz[None, :], axis=1)
    return np.exp(-(d ** 2) / (2 * spread ** 2))


# Approximate source locations, in the montage's coordinate frame.
SOURCES = {
    "occipital": np.array([0.000, -0.095, 0.010]),
    "parietal":  np.array([0.000, -0.045, 0.090]),
    "central":   np.array([0.000,  0.005, 0.100]),
    "frontal":   np.array([0.000,  0.075, 0.045]),
    "temp_left": np.array([-0.070, -0.010, 0.030]),
    "temp_right": np.array([0.070, -0.010, 0.030]),
}


def simulate_recording(subject_idx: int, eyes_closed: bool,
                       sfreq: float = cfg.SFREQ,
                       duration: float = DURATION_S) -> np.ndarray:
    """Return an (n_channels, n_times) array in volts.

    Built as a small set of spatially extended sources projected onto the
    sensor array, rather than as independent per-channel noise.  That gives the
    montage a realistic correlation structure, which the bad-channel detector
    depends on and which independent noise would destroy.
    """
    seed = cfg.RANDOM_SEED + 1000 * subject_idx + int(eyes_closed)
    rng = np.random.default_rng(seed)
    n = int(round(duration * sfreq))
    n_ch = len(CHANNELS_10_10)
    t = np.arange(n) / sfreq

    # Participant-level traits, so leakage tests have something to detect.
    subj_gain = rng.uniform(0.8, 1.3)
    subj_iaf = ALPHA_HZ + rng.uniform(-1.2, 1.2)
    subj_alpha_strength = rng.uniform(0.6, 1.6)

    data = np.zeros((n_ch, n))

    # Broadband background from every source location.
    for xyz in SOURCES.values():
        data += _leadfield(xyz)[:, None] * (
            18e-6 * subj_gain * _pink(rng, n, sfreq))[None, :]

    # The planted effect: an occipital alpha generator that grows on eye
    # closure, with a weaker parietal partner.
    alpha_gain = 4.0 if eyes_closed else 1.0
    for name, amp in (("occipital", 9.0e-6), ("parietal", 3.5e-6)):
        data += _leadfield(SOURCES[name])[:, None] * _alpha_bump(
            rng, n, sfreq, subj_iaf,
            amp * alpha_gain * subj_alpha_strength * subj_gain)[None, :]

    # Slow drift, shared across the head, removed later by the 1 Hz high-pass.
    drift = 10e-6 * np.sin(2 * np.pi * rng.uniform(0.05, 0.4) * t)
    data += drift[None, :] * rng.uniform(0.6, 1.0, size=(n_ch, 1))

    # Blink-like transients from a frontal source, commoner with eyes open.
    blink_w = _leadfield(SOURCES["frontal"], spread=0.045)
    for _ in range(rng.poisson(3 if eyes_closed else 11)):
        c = rng.integers(0, n)
        half = int(0.25 * sfreq)
        lo, hi = max(0, c - half), min(n, c + half)
        data[:, lo:hi] += blink_w[:, None] * (
            np.hanning(hi - lo)[None, :] * rng.uniform(90e-6, 170e-6))

    # Small independent sensor noise, on top of the correlated sources.
    data += 1.5e-6 * rng.standard_normal((n_ch, n))

    # One dead electrode on some participants, so detection has a true positive.
    if subject_idx % 7 == 3:
        data[rng.integers(0, n_ch)] = rng.standard_normal(n) * 1e-9

    # Whole-head movement artifacts, so epoch rejection has something to reject.
    for _ in range(rng.integers(1, 4)):
        c = rng.integers(0, n)
        half = int(0.6 * sfreq)
        lo, hi = max(0, c - half), min(n, c + half)
        data[:, lo:hi] += np.hanning(hi - lo)[None, :] * rng.uniform(
            200e-6, 500e-6, size=(n_ch, 1))

    return data


def write_edf(path: Path, data: np.ndarray, sfreq: float) -> None:
    import mne

    info = mne.create_info(CHANNELS_10_10, sfreq, ch_types="eeg", verbose="error")
    raw = mne.io.RawArray(data, info, verbose="error")
    path.parent.mkdir(parents=True, exist_ok=True)
    # physical_range is interpreted in MICROVOLTS by MNE's EDF exporter, not
    # in volts.  Passing (-0.01, 0.01) here clips every sample to +/-0.01 uV,
    # which silently zeroes every band power downstream.  "auto" derives the
    # range from the data and is the safe choice.
    mne.export.export_raw(str(path), raw, fmt="edf", overwrite=True,
                          physical_range="auto", verbose="error")


def build_fixture(n_subjects: int = 12) -> list[Path]:
    written: list[Path] = []
    for i in range(1, n_subjects + 1):
        subject = f"S{i:03d}"
        for run, cond in cfg.RUNS.items():
            path = cfg.RAW / subject / f"{subject}{run}.edf"
            data = simulate_recording(i, eyes_closed=(cond == "eyes_closed"))
            write_edf(path, data, cfg.SFREQ)
            written.append(path)
        print(f"  fixture {subject}: {len(cfg.RUNS)} runs")
    print(f"SYNTHETIC fixture written: {len(written)} files under {cfg.RAW}")
    return written


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    build_fixture(n)
